# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    feedsToUse: config
    nugetConfigPath: NuGet.config  
    arguments: '-r linux-x64'

- task: ado-discord-webhook@1
  inputs:
    channelId: '712310078820057138'
    webhookKey: 'bqrqx2QXxwfqxYby3smfR1iutltWv39bmQdJPMsqMDJdPLLMD9Z3vazP5SfEkM1AU7vy'
    name: 'hook'
    messageType: 'embeds'
    embeds: |
          {
            "embeds": [
              {
                "description": "some stuff",
                "url": "https://discordapp.com",
                "color": 4437377,
                "author": {
                  "name": "Build Succeeded",
                  "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png"
                }
              }
            ]
          }
        